/* tslint:disable */
/* eslint-disable */
/**
 * API Specification
 * クライアント-サーバー間のデータ通信仕様
 *
 * The version of the OpenAPI document: 0.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Choice,
    ChoiceFromJSON,
    ChoiceFromJSONTyped,
    ChoiceToJSON,
} from '.';

/**
 *
 * @export
 * @interface InspectionItem
 */
export interface InspectionItem {
    /**
     *
     * @type {number}
     * @memberof InspectionItem
     */
    inspection_item_id: number;
    /**
     *
     * @type {number}
     * @memberof InspectionItem
     */
    order_index: number;
    /**
     *
     * @type {string}
     * @memberof InspectionItem
     */
    inspection_content: string;
    /**
     *
     * @type {number}
     * @memberof InspectionItem
     */
    input_type: number;
    /**
     *
     * @type {Array<Choice>}
     * @memberof InspectionItem
     */
    choices?: Array<Choice>;
}

export function InspectionItemFromJSON(json: any): InspectionItem {
    return InspectionItemFromJSONTyped(json, false);
}

export function InspectionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectionItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'inspection_item_id': json['inspection_item_id'],
        'order_index': json['order_index'],
        'inspection_content': json['inspection_content'],
        'input_type': json['input_type'],
        'choices': !exists(json, 'choices') ? undefined : ((json['choices'] as Array<any>).map(ChoiceFromJSON)),
    };
}

export function InspectionItemToJSON(value?: InspectionItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'inspection_item_id': value.inspection_item_id,
        'order_index': value.order_index,
        'inspection_content': value.inspection_content,
        'input_type': value.input_type,
        'choices': value.choices === undefined ? undefined : ((value.choices as Array<any>).map(ChoiceToJSON)),
    };
}


