/* tslint:disable */
/* eslint-disable */
/**
 * API Specification
 * クライアント-サーバー間のデータ通信仕様
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Equipment,
    EquipmentFromJSON,
    EquipmentFromJSONTyped,
    EquipmentToJSON,
} from './';

/**
 * 
 * @export
 * @interface InspectionSheetDetail
 */
export interface InspectionSheetDetail {
    /**
     * 
     * @type {number}
     * @memberof InspectionSheetDetail
     */
    sheet_id: number;
    /**
     * 
     * @type {string}
     * @memberof InspectionSheetDetail
     */
    sheet_name: string;
    /**
     * 
     * @type {number}
     * @memberof InspectionSheetDetail
     */
    inspection_type_id: number;
    /**
     * 
     * @type {number}
     * @memberof InspectionSheetDetail
     */
    inspection_group_id: number;
    /**
     * 
     * @type {Array<Equipment>}
     * @memberof InspectionSheetDetail
     */
    equipments: Array<Equipment>;
}

export function InspectionSheetDetailFromJSON(json: any): InspectionSheetDetail {
    return InspectionSheetDetailFromJSONTyped(json, false);
}

export function InspectionSheetDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectionSheetDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sheet_id': json['sheet_id'],
        'sheet_name': json['sheet_name'],
        'inspection_type_id': json['inspection_type_id'],
        'inspection_group_id': json['inspection_group_id'],
        'equipments': ((json['equipments'] as Array<any>).map(EquipmentFromJSON)),
    };
}

export function InspectionSheetDetailToJSON(value?: InspectionSheetDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sheet_id': value.sheet_id,
        'sheet_name': value.sheet_name,
        'inspection_type_id': value.inspection_type_id,
        'inspection_group_id': value.inspection_group_id,
        'equipments': ((value.equipments as Array<any>).map(EquipmentToJSON)),
    };
}


