/* tslint:disable */
/* eslint-disable */
/**
 * API Specification
 * クライアント-サーバー間のデータ通信仕様
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InspectionType
 */
export interface InspectionType {
    /**
     * 
     * @type {number}
     * @memberof InspectionType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InspectionType
     */
    description: string;
}

export function InspectionTypeFromJSON(json: any): InspectionType {
    return InspectionTypeFromJSONTyped(json, false);
}

export function InspectionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectionType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
    };
}

export function InspectionTypeToJSON(value?: InspectionType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
    };
}

