/* tslint:disable */
/* eslint-disable */
/**
 * Open API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models';

export interface ApiV1JsonInspectionSheetsIdGetRequest {
    id: number;
}

/**
 * 
 */
export class JsonExportApi extends runtime.BaseAPI {

    /**
     * エクセル形式で点検シートをダウンロードする
     */
    async apiV1JsonInspectionSheetsIdGetRaw(requestParameters: ApiV1JsonInspectionSheetsIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiV1JsonInspectionSheetsIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/json-inspection-sheets/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * エクセル形式で点検シートをダウンロードする
     */
    async apiV1JsonInspectionSheetsIdGet(requestParameters: ApiV1JsonInspectionSheetsIdGetRequest, initOverrides?: RequestInit): Promise<Blob> {
        const response = await this.apiV1JsonInspectionSheetsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
