@startuml class-diagram-client
package component {
  class Home
  class Layout
  class NavMenu
  ' relationship
  Layout ..> NavMenu
}
package categories {
  class InspectionGroupCategory
  class InspectionTypeCategory
  class ChoicesTemplate
  ' relationship
}
package inspection {
  class Create
  class Details
  class Edit
  class EquipmentForm
  class InspectionItemForm
  class InspectionItemRow
  package module {
    class InspectionItemReducer
    class InspectionSheetReducer
  }
  package operations {
    class InspectionSheetOperator
    class InspectionItemOperator
  }
  package contexts {
    class InspectionSheetContext
    class InspectionItemContext
  }
  package dialog {
    class ChoiceSetSelectDialog
    class InspectionItemDialog
    ' relationship
    InspectionItemDialog ..> ChoiceSetSelectDialog
  }
  ' relationship
  Create ..> InspectionSheetForm
  Edit ..> InspectionSheetForm
  InspectionSheetForm ..> EquipmentForm
  InspectionSheetForm ..> InspectionItemDialog
  EquipmentForm ..> InspectionItemForm
  InspectionItemForm ..> InspectionItemRow
  InspectionItemContext ..> InspectionItemOperator
  InspectionSheetContext ..> InspectionSheetOperator
  InspectionItemOperator ..> InspectionItemReducer
  InspectionSheetOperator ..> InspectionSheetReducer
}
class App

' relationship
App ..> Layout
App ..> Home
App ..> InspectionGroupCategory
App ..> InspectionTypeCategory
App ..> ChoicesTemplate
App ..> Create
App ..> Details
App ..> Edit

@enduml
