@startuml sequence-diagram

actor user
participant InpsectionSheetForm as sheetForm
participant EquipmentForm as equipForm
participant InpsectionItemForm as itemForm
participant InpsectionItemDialog as itemDialog
entity InspectionSheetContext as sheetContext
entity InspectionItemContext as itemContext

== Add New Equipment ==
user -> sheetForm : 点検機器追加ボタンをクリック
sheetForm -> sheetContext : 点検機器追加
sheetForm <-- sheetContext : 点検シート情報
sheetForm -> equipForm : 描画処理
equipForm -> itemForm : 描画処理
equipForm <-- itemForm : 表示結果
sheetForm <-- equipForm : 表示結果
user <-- sheetForm : 更新後の表示結果

== Remove Equipment ==
user -> equipForm : 点検機器削除ボタンをクリック
equipForm -> sheetContext : 点検機器削除
sheetForm <-- sheetContext : 点検シート情報
sheetForm -> equipForm : 描画処理
equipForm -> itemForm : 描画処理
equipForm <-- itemForm : 表示結果
sheetForm <-- equipForm : 表示結果
user <-- sheetForm : 更新後の表示結果

== Update Equipment ==
user -> equipForm : 点検機器情報編集
equipForm -> sheetContext : 点検機器情報編集
sheetForm <-- sheetContext : 点検シート情報
sheetForm -> equipForm : 描画処理
equipForm -> itemForm : 描画処理
equipForm <-- itemForm : 表示結果
sheetForm <-- equipForm : 表示結果
user <-- sheetForm : 更新後の表示結果

== Add Insepction Item ==
user -> equipForm : 点検項目追加ボタンをクリック
equipForm -> equipForm : 追加モードに設定
equipForm -> itemContext : 新規点検項目を設定
equipForm -> itemDialog : 点検項目ダイアログを開く
user <-- itemDialog : 点検項目ダイアロ表示
user ->  itemDialog : 点検項目編集
itemDialog -> itemContext : 点検項目編集
itemDialog <-- itemContext : 点検項目情報
user <-- itemDialog : 更新後の表示結果
alt 編集を適応する場合
  user ->  itemDialog : OKボタンをクリック
  itemDialog -> itemContext : 点検項目情報を取得
  itemDialog <-- itemContext : 点検項目情報
  itemDialog -> sheetContext : 点検項目を追加
  itemDialog -> itemDialog : 点検項目ダイアログを閉じる
  sheetForm <-- sheetContext : 点検シート情報
  sheetForm -> equipForm : 描画処理
  equipForm -> itemForm : 描画処理
  equipForm <-- itemForm : 表示結果
  sheetForm <-- equipForm : 表示結果
  user <-- sheetForm : 更新後の表示結果
else 編集を適応しない場合
  user ->  itemDialog : キャンセルボタンをクリック
  itemDialog -> itemDialog : 点検項目ダイアログを閉じる
end

@enduml
